#ifndef SOURCES_LIBCALLBACKS_WIDGETS_INCLUDE_WIDGETS_EXPORT_H_
#define SOURCES_LIBCALLBACKS_WIDGETS_INCLUDE_WIDGETS_EXPORT_H_

#ifndef LIB_STATIC_DEFINE
#  include <callbacks/export_shared.h>
#else
#  include <callbacks/export_static.h>
#endif


#endif //SOURCES_LIBCALLBACKS_WIDGETS_INCLUDE_WIDGETS_EXPORT_H_
